// NCAAF Oracle v4.1 — Logistic Regression Meta-Model
// Loads coefficients + scaler from data/model/ (generated by python/train_model.py).
// Falls back to Monte Carlo win probability if model not trained yet.
// P(home_win) = sigmoid(β0 + β1×elo_diff + β2×sp_plus_diff + ...)

import { readFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { logger } from '../logger.js';
import type { NCAAFFeatureVector } from '../types.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const MODEL_DIR = resolve(__dirname, '../../data/model');

// Feature names in exact training order (must match python/train_model.py)
export const FEATURE_NAMES = [
  'elo_diff',
  'sp_plus_diff',
  'sp_plus_off_diff',
  'sp_plus_def_diff',
  'sp_plus_st_diff',
  'fpi_diff',
  'pythagorean_diff',
  'qb_epa_diff',
  'pass_epa_diff',
  'rush_epa_diff',
  'off_epa_diff',
  'def_epa_diff',
  'success_rate_diff',
  'explosiveness_diff',
  'havoc_rate_diff',
  'finishing_drives_diff',
  'turnover_margin_diff',
  'line_yards_diff',
  'recruiting_composite_diff',
  'transfer_portal_impact_diff',
  'returning_production_diff',
  'team_recent_epa_diff',
  'rest_days_diff',
  'sos_diff',
  'is_neutral_site',
  'home_field_adj',
  'wind_adj',
  'precip_adj',
  'temp_adj',
  'is_rivalry',
  'is_conference_game',
  'is_bowl',
  'pace_diff',
  'coach_experience_diff',
  'injury_qb_flag_home',
  'injury_qb_flag_away',
  'vegas_home_prob',
  'mc_win_pct',
] as const;

interface ModelCoefficients {
  intercept: number;
  coefficients: number[];
  feature_names: string[];
}

interface ModelScaler {
  mean: number[];
  scale: number[];
  feature_names: string[];
}

interface CalibrationMap {
  x_thresholds: number[];
  y_thresholds: number[];
}

interface ModelMetadata {
  version: string;
  train_seasons: string;
  avg_brier: number;
  avg_accuracy: number;
  n_features: number;
  trained_at: string;
}

let _model: ModelCoefficients | null = null;
let _scaler: ModelScaler | null = null;
let _calibration: CalibrationMap | null = null;
let _metadata: ModelMetadata | null = null;

// ─── Load model artifacts ─────────────────────────────────────────────────────

export function loadModel(): boolean {
  const coeffPath = resolve(MODEL_DIR, 'coefficients.json');
  const scalerPath = resolve(MODEL_DIR, 'scaler.json');
  const calibPath = resolve(MODEL_DIR, 'calibration.json');
  const metaPath = resolve(MODEL_DIR, 'metadata.json');

  if (!existsSync(coeffPath)) {
    logger.warn('Model coefficients not found. Using Monte Carlo fallback.');
    return false;
  }

  try {
    _model = JSON.parse(readFileSync(coeffPath, 'utf-8')) as ModelCoefficients;
    if (existsSync(scalerPath)) _scaler = JSON.parse(readFileSync(scalerPath, 'utf-8')) as ModelScaler;
    if (existsSync(calibPath)) _calibration = JSON.parse(readFileSync(calibPath, 'utf-8')) as CalibrationMap;
    if (existsSync(metaPath)) _metadata = JSON.parse(readFileSync(metaPath, 'utf-8')) as ModelMetadata;
    logger.info({ version: _metadata?.version, trained_at: _metadata?.trained_at }, 'Model loaded');
    return true;
  } catch (err) {
    logger.error({ err }, 'Failed to load model');
    return false;
  }
}

// ─── Sigmoid ──────────────────────────────────────────────────────────────────

function sigmoid(x: number): number {
  return 1 / (1 + Math.exp(-x));
}

// ─── Feature vector to array ──────────────────────────────────────────────────

function featuresToArray(features: NCAAFFeatureVector): number[] {
  return FEATURE_NAMES.map(name => {
    const val = (features as unknown as Record<string, number>)[name];
    return val ?? 0;
  });
}

// ─── Standard scaling ────────────────────────────────────────────────────────

function scaleFeatures(raw: number[], scaler: ModelScaler): number[] {
  return raw.map((v, i) => (v - (scaler.mean[i] ?? 0)) / (scaler.scale[i] ?? 1));
}

// ─── Platt calibration (isotonic regression via linear interpolation) ─────────

function applyCalibration(rawProb: number, calibration: CalibrationMap): number {
  const { x_thresholds, y_thresholds } = calibration;
  if (rawProb <= x_thresholds[0]) return y_thresholds[0];
  if (rawProb >= x_thresholds[x_thresholds.length - 1]) return y_thresholds[y_thresholds.length - 1];

  for (let i = 0; i < x_thresholds.length - 1; i++) {
    if (rawProb >= x_thresholds[i] && rawProb <= x_thresholds[i + 1]) {
      const t = (rawProb - x_thresholds[i]) / (x_thresholds[i + 1] - x_thresholds[i]);
      return y_thresholds[i] + t * (y_thresholds[i + 1] - y_thresholds[i]);
    }
  }
  return rawProb;
}

// ─── Predict ─────────────────────────────────────────────────────────────────

export function predict(features: NCAAFFeatureVector, mcWinPct: number): number {
  if (!_model) {
    // Fallback: blend Monte Carlo with a simple Elo-based estimate
    const eloProb = sigmoid(features.elo_diff / 200);
    const spProb = sigmoid(features.sp_plus_diff / 10);
    const blended = 0.5 * mcWinPct + 0.3 * eloProb + 0.2 * spProb;
    return Math.max(0.05, Math.min(0.95, blended));
  }

  const featureArray = featuresToArray({ ...features, mc_win_pct: mcWinPct });
  const scaled = _scaler ? scaleFeatures(featureArray, _scaler) : featureArray;

  // Logistic regression: z = intercept + sum(coeff_i * x_i)
  let z = _model.intercept;
  for (let i = 0; i < _model.coefficients.length; i++) {
    z += _model.coefficients[i] * (scaled[i] ?? 0);
  }

  const rawProb = sigmoid(z);
  const calibrated = _calibration ? applyCalibration(rawProb, _calibration) : rawProb;
  return Math.max(0.05, Math.min(0.95, calibrated));
}

export function isModelLoaded(): boolean {
  return _model !== null;
}

export function getModelVersion(): string {
  return _metadata?.version ?? 'fallback';
}

export function getModelMetadata(): ModelMetadata | null {
  return _metadata;
}
